apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-ms

resources:
  - ../../base
  - ../../postgres

images:
  - name: ghcr.io/gauravv/dev-go-ms-api
    newName: ghcr.io/gauravv/dev-go-ms-api
    newTag: local
