apiVersion: v1
kind: ConfigMap
metadata:
  name: go-ms-config
data:
  port: "8080"
  auth_enabled: "true"
  log_level: "info"
  allowed_origins: "https://dev-go-ms-api.gauravv.dev"
  istio_enabled: "true"
