apiVersion: v1
kind: Service
metadata:
  name: go-ms
  labels:
    app: go-ms
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: go-ms
